import { Tile, MahjongTileCategory } from '../models/tile';

export const mockMahjongBoard: Tile[][] = [
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: false, isMatched: false, display: "[Bam-0]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: false, isMatched: false, display: "[Bam-0]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: false, isMatched: false, display: "[Bam-0]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: false, isMatched: false, display: "[Bam-0]" },
    { category: MahjongTileCategory.Bamboo, value: 1, isRemoved: false, isMatched: false, display: "[Bam-1]" },
    { category: MahjongTileCategory.Bamboo, value: 1, isRemoved: false, isMatched: false, display: "[Bam-1]" },
    { category: MahjongTileCategory.Bamboo, value: 1, isRemoved: false, isMatched: false, display: "[Bam-1]" },
    { category: MahjongTileCategory.Bamboo, value: 1, isRemoved: false, isMatched: false, display: "[Bam-1]" },
    { category: MahjongTileCategory.Bamboo, value: 2, isRemoved: false, isMatched: false, display: "[Bam-2]" },
    { category: MahjongTileCategory.Bamboo, value: 2, isRemoved: false, isMatched: false, display: "[Bam-2]" },
    { category: MahjongTileCategory.Bamboo, value: 2, isRemoved: false, isMatched: false, display: "[Bam-2]" },
    { category: MahjongTileCategory.Bamboo, value: 2, isRemoved: false, isMatched: false, display: "[Bam-2]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 3, isRemoved: false, isMatched: false, display: "[Bam-3]" },
    { category: MahjongTileCategory.Bamboo, value: 3, isRemoved: false, isMatched: false, display: "[Bam-3]" },
    { category: MahjongTileCategory.Bamboo, value: 3, isRemoved: false, isMatched: false, display: "[Bam-3]" },
    { category: MahjongTileCategory.Bamboo, value: 3, isRemoved: false, isMatched: false, display: "[Bam-3]" },
    { category: MahjongTileCategory.Bamboo, value: 4, isRemoved: false, isMatched: false, display: "[Bam-4]" },
    { category: MahjongTileCategory.Bamboo, value: 4, isRemoved: false, isMatched: false, display: "[Bam-4]" },
    { category: MahjongTileCategory.Bamboo, value: 4, isRemoved: false, isMatched: false, display: "[Bam-4]" },
    { category: MahjongTileCategory.Bamboo, value: 4, isRemoved: false, isMatched: false, display: "[Bam-4]" },
    { category: MahjongTileCategory.Bamboo, value: 5, isRemoved: false, isMatched: false, display: "[Bam-5]" },
    { category: MahjongTileCategory.Bamboo, value: 5, isRemoved: false, isMatched: false, display: "[Bam-5]" },
    { category: MahjongTileCategory.Bamboo, value: 5, isRemoved: false, isMatched: false, display: "[Bam-5]" },
    { category: MahjongTileCategory.Bamboo, value: 5, isRemoved: false, isMatched: false, display: "[Bam-5]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 6, isRemoved: false, isMatched: false, display: "[Bam-6]" },
    { category: MahjongTileCategory.Bamboo, value: 6, isRemoved: false, isMatched: false, display: "[Bam-6]" },
    { category: MahjongTileCategory.Bamboo, value: 6, isRemoved: false, isMatched: false, display: "[Bam-6]" },
    { category: MahjongTileCategory.Bamboo, value: 6, isRemoved: false, isMatched: false, display: "[Bam-6]" },
    { category: MahjongTileCategory.Bamboo, value: 7, isRemoved: false, isMatched: false, display: "[Bam-7]" },
    { category: MahjongTileCategory.Bamboo, value: 7, isRemoved: false, isMatched: false, display: "[Bam-7]" },
    { category: MahjongTileCategory.Bamboo, value: 7, isRemoved: false, isMatched: false, display: "[Bam-7]" },
    { category: MahjongTileCategory.Bamboo, value: 7, isRemoved: false, isMatched: false, display: "[Bam-7]" },
    { category: MahjongTileCategory.Bamboo, value: 8, isRemoved: false, isMatched: false, display: "[Bam-8]" },
    { category: MahjongTileCategory.Bamboo, value: 8, isRemoved: false, isMatched: false, display: "[Bam-8]" },
    { category: MahjongTileCategory.Bamboo, value: 8, isRemoved: false, isMatched: false, display: "[Bam-8]" },
    { category: MahjongTileCategory.Bamboo, value: 8, isRemoved: false, isMatched: false, display: "[Bam-8]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Circles, value: 0, isRemoved: false, isMatched: false, display: "[Cir-0]" },
    { category: MahjongTileCategory.Circles, value: 0, isRemoved: false, isMatched: false, display: "[Cir-0]" },
    { category: MahjongTileCategory.Circles, value: 0, isRemoved: false, isMatched: false, display: "[Cir-0]" },
    { category: MahjongTileCategory.Circles, value: 0, isRemoved: false, isMatched: false, display: "[Cir-0]" },
    { category: MahjongTileCategory.Circles, value: 1, isRemoved: false, isMatched: false, display: "[Cir-1]" },
    { category: MahjongTileCategory.Circles, value: 1, isRemoved: false, isMatched: false, display: "[Cir-1]" },
    { category: MahjongTileCategory.Circles, value: 1, isRemoved: false, isMatched: false, display: "[Cir-1]" },
    { category: MahjongTileCategory.Circles, value: 1, isRemoved: false, isMatched: false, display: "[Cir-1]" },
    { category: MahjongTileCategory.Circles, value: 2, isRemoved: false, isMatched: false, display: "[Cir-2]" },
    { category: MahjongTileCategory.Circles, value: 2, isRemoved: false, isMatched: false, display: "[Cir-2]" },
    { category: MahjongTileCategory.Circles, value: 2, isRemoved: false, isMatched: false, display: "[Cir-2]" },
    { category: MahjongTileCategory.Circles, value: 2, isRemoved: false, isMatched: false, display: "[Cir-2]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Circles, value: 3, isRemoved: false, isMatched: false, display: "[Cir-3]" },
    { category: MahjongTileCategory.Circles, value: 3, isRemoved: false, isMatched: false, display: "[Cir-3]" },
    { category: MahjongTileCategory.Circles, value: 3, isRemoved: false, isMatched: false, display: "[Cir-3]" },
    { category: MahjongTileCategory.Circles, value: 3, isRemoved: false, isMatched: false, display: "[Cir-3]" },
    { category: MahjongTileCategory.Circles, value: 4, isRemoved: false, isMatched: false, display: "[Cir-4]" },
    { category: MahjongTileCategory.Circles, value: 4, isRemoved: false, isMatched: false, display: "[Cir-4]" },
    { category: MahjongTileCategory.Circles, value: 4, isRemoved: false, isMatched: false, display: "[Cir-4]" },
    { category: MahjongTileCategory.Circles, value: 4, isRemoved: false, isMatched: false, display: "[Cir-4]" },
    { category: MahjongTileCategory.Circles, value: 5, isRemoved: false, isMatched: false, display: "[Cir-5]" },
    { category: MahjongTileCategory.Circles, value: 5, isRemoved: false, isMatched: false, display: "[Cir-5]" },
    { category: MahjongTileCategory.Circles, value: 5, isRemoved: false, isMatched: false, display: "[Cir-5]" },
    { category: MahjongTileCategory.Circles, value: 5, isRemoved: false, isMatched: false, display: "[Cir-5]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Circles, value: 6, isRemoved: false, isMatched: false, display: "[Cir-6]" },
    { category: MahjongTileCategory.Circles, value: 6, isRemoved: false, isMatched: false, display: "[Cir-6]" },
    { category: MahjongTileCategory.Circles, value: 6, isRemoved: false, isMatched: false, display: "[Cir-6]" },
    { category: MahjongTileCategory.Circles, value: 6, isRemoved: false, isMatched: false, display: "[Cir-6]" },
    { category: MahjongTileCategory.Circles, value: 7, isRemoved: false, isMatched: false, display: "[Cir-7]" },
    { category: MahjongTileCategory.Circles, value: 7, isRemoved: false, isMatched: false, display: "[Cir-7]" },
    { category: MahjongTileCategory.Circles, value: 7, isRemoved: false, isMatched: false, display: "[Cir-7]" },
    { category: MahjongTileCategory.Circles, value: 7, isRemoved: false, isMatched: false, display: "[Cir-7]" },
    { category: MahjongTileCategory.Circles, value: 8, isRemoved: false, isMatched: false, display: "[Cir-8]" },
    { category: MahjongTileCategory.Circles, value: 8, isRemoved: false, isMatched: false, display: "[Cir-8]" },
    { category: MahjongTileCategory.Circles, value: 8, isRemoved: false, isMatched: false, display: "[Cir-8]" },
    { category: MahjongTileCategory.Circles, value: 8, isRemoved: false, isMatched: false, display: "[Cir-8]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Characters, value: 0, isRemoved: false, isMatched: false, display: "[Cha-0]" },
    { category: MahjongTileCategory.Characters, value: 0, isRemoved: false, isMatched: false, display: "[Cha-0]" },
    { category: MahjongTileCategory.Characters, value: 0, isRemoved: false, isMatched: false, display: "[Cha-0]" },
    { category: MahjongTileCategory.Characters, value: 0, isRemoved: false, isMatched: false, display: "[Cha-0]" },
    { category: MahjongTileCategory.Characters, value: 1, isRemoved: false, isMatched: false, display: "[Cha-1]" },
    { category: MahjongTileCategory.Characters, value: 1, isRemoved: false, isMatched: false, display: "[Cha-1]" },
    { category: MahjongTileCategory.Characters, value: 1, isRemoved: false, isMatched: false, display: "[Cha-1]" },
    { category: MahjongTileCategory.Characters, value: 1, isRemoved: false, isMatched: false, display: "[Cha-1]" },
    { category: MahjongTileCategory.Characters, value: 2, isRemoved: false, isMatched: false, display: "[Cha-2]" },
    { category: MahjongTileCategory.Characters, value: 2, isRemoved: false, isMatched: false, display: "[Cha-2]" },
    { category: MahjongTileCategory.Characters, value: 2, isRemoved: false, isMatched: false, display: "[Cha-2]" },
    { category: MahjongTileCategory.Characters, value: 2, isRemoved: false, isMatched: false, display: "[Cha-2]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Characters, value: 3, isRemoved: false, isMatched: false, display: "[Cha-3]" },
    { category: MahjongTileCategory.Characters, value: 3, isRemoved: false, isMatched: false, display: "[Cha-3]" },
    { category: MahjongTileCategory.Characters, value: 3, isRemoved: false, isMatched: false, display: "[Cha-3]" },
    { category: MahjongTileCategory.Characters, value: 3, isRemoved: false, isMatched: false, display: "[Cha-3]" },
    { category: MahjongTileCategory.Characters, value: 4, isRemoved: false, isMatched: false, display: "[Cha-4]" },
    { category: MahjongTileCategory.Characters, value: 4, isRemoved: false, isMatched: false, display: "[Cha-4]" },
    { category: MahjongTileCategory.Characters, value: 4, isRemoved: false, isMatched: false, display: "[Cha-4]" },
    { category: MahjongTileCategory.Characters, value: 4, isRemoved: false, isMatched: false, display: "[Cha-4]" },
    { category: MahjongTileCategory.Characters, value: 5, isRemoved: false, isMatched: false, display: "[Cha-5]" },
    { category: MahjongTileCategory.Characters, value: 5, isRemoved: false, isMatched: false, display: "[Cha-5]" },
    { category: MahjongTileCategory.Characters, value: 5, isRemoved: false, isMatched: false, display: "[Cha-5]" },
    { category: MahjongTileCategory.Characters, value: 5, isRemoved: false, isMatched: false, display: "[Cha-5]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Characters, value: 6, isRemoved: false, isMatched: false, display: "[Cha-6]" },
    { category: MahjongTileCategory.Characters, value: 6, isRemoved: false, isMatched: false, display: "[Cha-6]" },
    { category: MahjongTileCategory.Characters, value: 6, isRemoved: false, isMatched: false, display: "[Cha-6]" },
    { category: MahjongTileCategory.Characters, value: 6, isRemoved: false, isMatched: false, display: "[Cha-6]" },
    { category: MahjongTileCategory.Characters, value: 7, isRemoved: false, isMatched: false, display: "[Cha-7]" },
    { category: MahjongTileCategory.Characters, value: 7, isRemoved: false, isMatched: false, display: "[Cha-7]" },
    { category: MahjongTileCategory.Characters, value: 7, isRemoved: false, isMatched: false, display: "[Cha-7]" },
    { category: MahjongTileCategory.Characters, value: 7, isRemoved: false, isMatched: false, display: "[Cha-7]" },
    { category: MahjongTileCategory.Characters, value: 8, isRemoved: false, isMatched: false, display: "[Cha-8]" },
    { category: MahjongTileCategory.Characters, value: 8, isRemoved: false, isMatched: false, display: "[Cha-8]" },
    { category: MahjongTileCategory.Characters, value: 8, isRemoved: false, isMatched: false, display: "[Cha-8]" },
    { category: MahjongTileCategory.Characters, value: 8, isRemoved: false, isMatched: false, display: "[Cha-8]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Winds, value: 0, isRemoved: false, isMatched: false, display: "[Win-0]" },
    { category: MahjongTileCategory.Winds, value: 0, isRemoved: false, isMatched: false, display: "[Win-0]" },
    { category: MahjongTileCategory.Winds, value: 0, isRemoved: false, isMatched: false, display: "[Win-0]" },
    { category: MahjongTileCategory.Winds, value: 0, isRemoved: false, isMatched: false, display: "[Win-0]" },
    { category: MahjongTileCategory.Winds, value: 1, isRemoved: false, isMatched: false, display: "[Win-1]" },
    { category: MahjongTileCategory.Winds, value: 1, isRemoved: false, isMatched: false, display: "[Win-1]" },
    { category: MahjongTileCategory.Winds, value: 1, isRemoved: false, isMatched: false, display: "[Win-1]" },
    { category: MahjongTileCategory.Winds, value: 1, isRemoved: false, isMatched: false, display: "[Win-1]" },
    { category: MahjongTileCategory.Winds, value: 2, isRemoved: false, isMatched: false, display: "[Win-2]" },
    { category: MahjongTileCategory.Winds, value: 2, isRemoved: false, isMatched: false, display: "[Win-2]" },
    { category: MahjongTileCategory.Winds, value: 2, isRemoved: false, isMatched: false, display: "[Win-2]" },
    { category: MahjongTileCategory.Winds, value: 2, isRemoved: false, isMatched: false, display: "[Win-2]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Winds, value: 3, isRemoved: false, isMatched: false, display: "[Win-3]" },
    { category: MahjongTileCategory.Winds, value: 3, isRemoved: false, isMatched: false, display: "[Win-3]" },
    { category: MahjongTileCategory.Winds, value: 3, isRemoved: false, isMatched: false, display: "[Win-3]" },
    { category: MahjongTileCategory.Winds, value: 3, isRemoved: false, isMatched: false, display: "[Win-3]" },
    { category: MahjongTileCategory.Dragons, value: 0, isRemoved: false, isMatched: false, display: "[Dra-0]" },
    { category: MahjongTileCategory.Dragons, value: 0, isRemoved: false, isMatched: false, display: "[Dra-0]" },
    { category: MahjongTileCategory.Dragons, value: 0, isRemoved: false, isMatched: false, display: "[Dra-0]" },
    { category: MahjongTileCategory.Dragons, value: 0, isRemoved: false, isMatched: false, display: "[Dra-0]" },
    { category: MahjongTileCategory.Dragons, value: 1, isRemoved: false, isMatched: false, display: "[Dra-1]" },
    { category: MahjongTileCategory.Dragons, value: 1, isRemoved: false, isMatched: false, display: "[Dra-1]" },
    { category: MahjongTileCategory.Dragons, value: 1, isRemoved: false, isMatched: false, display: "[Dra-1]" },
    { category: MahjongTileCategory.Dragons, value: 1, isRemoved: false, isMatched: false, display: "[Dra-1]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Dragons, value: 2, isRemoved: false, isMatched: false, display: "[Dra-2]" },
    { category: MahjongTileCategory.Dragons, value: 2, isRemoved: false, isMatched: false, display: "[Dra-2]" },
    { category: MahjongTileCategory.Dragons, value: 2, isRemoved: false, isMatched: false, display: "[Dra-2]" },
    { category: MahjongTileCategory.Dragons, value: 2, isRemoved: false, isMatched: false, display: "[Dra-2]" },
    { category: MahjongTileCategory.Flowers, value: 1, isRemoved: false, isMatched: false, display: "[Flo-1]" },
    { category: MahjongTileCategory.Flowers, value: 1, isRemoved: false, isMatched: false, display: "[Flo-1]" },
    { category: MahjongTileCategory.Flowers, value: 1, isRemoved: false, isMatched: false, display: "[Flo-1]" },
    { category: MahjongTileCategory.Flowers, value: 1, isRemoved: false, isMatched: false, display: "[Flo-1]" },
    { category: MahjongTileCategory.Seasons, value: 1, isRemoved: false, isMatched: false, display: "[Sea-1]" },
    { category: MahjongTileCategory.Seasons, value: 1, isRemoved: false, isMatched: false, display: "[Sea-1]" },
    { category: MahjongTileCategory.Seasons, value: 1, isRemoved: false, isMatched: false, display: "[Sea-1]" },
    { category: MahjongTileCategory.Seasons, value: 1, isRemoved: false, isMatched: false, display: "[Sea-1]" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ],
  [
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" },
    { category: MahjongTileCategory.Bamboo, value: 0, isRemoved: true, isMatched: false, display: "" }
  ]
];