name: Ultimate-Mahjong-Connect-Front CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: ultimate-mahjong-connect-front
  K8S_NAMESPACE: ultimate-mahjong-connect

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ultimate-mahjong-connect/package-lock.json
        
    - name: Install dependencies
      working-directory: ./ultimate-mahjong-connect
      run: npm ci
        
    - name: Run tests
      working-directory: ./ultimate-mahjong-connect
      continue-on-error: true
      run: npm test -- --browsers=ChromeHeadless --watch=false --no-progress
        
    - name: Build application
      working-directory: ./ultimate-mahjong-connect
      run: npm run build
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0 

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./ultimate-mahjong-connect
        platforms: linux/amd64,linux/arm64 
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ultimate-mahjong-connect-front-image:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 
        
      - name: Deploy to Raspberry Pi
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/${{ github.repository_owner }}/ultimate-mahjong-connect-front-image:latest
          
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/ --validate=false
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=ghcr.io/${{ github.repository_owner }}/ultimate-mahjong-connect-front-image:latest -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.K8S_NAMESPACE }} 